
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Cards').del()
  .then(function () {
      // Inserts seed entries
      return knex('Cards').insert([
        { ID: 1, Number: 1,Color: 'Red'},
        { ID: 2, Number: 2,Color: 'Red'},
        { ID: 3, Number: 3,Color: 'Red'},
        { ID: 4, Number: 4,Color: 'Red'},
        { ID: 5, Number: 5,Color: 'Red'},
        { ID: 6, Number: 6,Color: 'Red'},
        { ID: 7, Number: 7,Color: 'Red'},
        { ID: 8, Number: 8,Color: 'Red'},
        { ID: 9, Number: 9,Color: 'Red'},
        { ID: 10, Number: 10,Color: 'Red'},
        { ID: 11, Number: 11,Color: 'Red'},
        { ID: 12, Number: 12,Color: 'Red'},
        { ID: 13, Number: 1,Color: 'Yellow'},
        { ID: 14, Number: 2,Color: 'Yellow'},
        { ID: 15, Number: 3,Color: 'Yellow'},
        { ID: 16, Number: 4,Color: 'Yellow'},
        { ID: 17, Number: 5,Color: 'Yellow'},
        { ID: 18, Number: 6,Color: 'Yellow'},
        { ID: 19, Number: 7,Color: 'Yellow'},
        { ID: 20, Number: 8,Color: 'Yellow'},
        { ID: 21, Number: 9,Color: 'Yellow'},
        { ID: 22, Number: 10,Color: 'Yellow'},
        { ID: 23, Number: 11,Color: 'Yellow'},
        { ID: 24, Number: 12,Color: 'Yellow'},
        { ID: 25, Number: 1,Color: 'Green'},
        { ID: 26, Number: 2,Color: 'Green'},
        { ID: 27, Number: 3,Color: 'Green'},
        { ID: 28, Number: 4,Color: 'Green'},
        { ID: 29, Number: 5,Color: 'Green'},
        { ID: 30, Number: 6,Color: 'Green'},
        { ID: 31, Number: 7,Color: 'Green'},
        { ID: 32, Number: 8,Color: 'Green'},
        { ID: 33, Number: 9,Color: 'Green'},
        { ID: 34, Number: 10,Color: 'Green'},
        { ID: 35, Number: 11,Color: 'Green'},
        { ID: 36, Number: 12,Color: 'Green'},
        { ID: 37, Number: 1,Color: 'Blue'},
        { ID: 38, Number: 2,Color: 'Blue'},
        { ID: 39, Number: 3,Color: 'Blue'},
        { ID: 40, Number: 4,Color: 'Blue'},
        { ID: 41, Number: 5,Color: 'Blue'},
        { ID: 42, Number: 6,Color: 'Blue'},
        { ID: 43, Number: 7,Color: 'Blue'},
        { ID: 44, Number: 8,Color: 'Blue'},
        { ID: 45, Number: 9,Color: 'Blue'},
        { ID: 46, Number: 10,Color: 'Blue'},
        { ID: 47, Number: 11,Color: 'Blue'},
        { ID: 48, Number: 12,Color: 'Blue'},
        { ID: 49, Number: 0,Color: 'Red'},
        { ID: 50, Number: 0,Color: 'Yellow'},
        { ID: 51, Number: 0,Color: 'Green'},
        { ID: 52, Number: 0,Color: 'Blue'},
        { ID: 53, Number: 1,Color: 'WildCard'},
        { ID: 54, Number: 2,Color: 'WildCard'},
        ]);
  });
};
